# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Creates notes"
  lane :create_notes do |options|
    isReleasable = analyze_commits(match: "builds/*")

    notes = conventional_changelog(format: 'markdown', debug: true, commit_url: "https://github.com/Mause/ChooseFood/commit")
    File.open("metadata/android/en-GB/changelogs/#{options[:build_number]}.txt","w") {
      |file| file.write(notes)
    };
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|
    # google_play_track_version_codes
    # google_play_track_release_names
    create_notes
    add_git_tag(build_number: "1.0.0+#{options[:build_number]}")
    push_git_tags
    upload_to_play_store(
      aab: "build/app/outputs/bundle/release/app-release.aab",
      track: "internal"
    )
    firebase_app_distribution(
      app: "1:368264902347:android:1d391b2bfa5f9bd1264d4e",
      testers: "jack.thatch@gmail.com",
      android_artifact_path: "build/app/outputs/bundle/release/app-release.aab"
    )
    notify()
  end
  desc "Validate json key"
  lane :validate do
    validate_play_store_json_key
  end
end

desc "Notify via messaging services"
lane :notify do |options|
  line_notify(
    access_token: ENV["LINE_TOKEN"],
    message: "Choose Food version 1.0.0+#{options[:build_number]} has been pushed to firebase 💜"
  )
end
