name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  issue_opened_and_reopened:
    name: issue_opened_and_reopened
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/Mause/projects/3
          github-token: ${{ secrets.ACCESS_TOKEN }}
