name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/users/Mause/projects/3'
