name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  issue_opened_and_reopened:
    name: issue_opened_and_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened' || github.event.action == 'reopened'
    steps:
      - name: 'Move issue to "Todo"'
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_token: ${{ secrets.ACCESS_TOKEN }}
          user: Mause
          project_id: 3
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "Todo"

  pr_opened_reopened_review_requested:
    name: pr_opened_reopened_review_requested
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'review_requested'
    steps:
      - name: 'Move PR to "In Progress"'
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_token: ${{ secrets.ACCESS_TOKEN }}
          user: Mause
          project_id: 3
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: "In Progress"
