# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

jobs:
  build:
    uses: Mause/ChooseFood/.github/workflows/reuse.yaml@main

  build_releases:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [appbundle, web]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Install dependencies
        run: flutter pub get
      - name: Prebuild
        run: flutter pub run build_runner build
      - if: ${{ matrix.target == 'appbundle' }}
        run: flutter build appbundle --build-number ${{ github.run_number }}
      - if: ${{ matrix.target == 'web' }}
        run: flutter build web
      - if: ${{ matrix.target == 'appbundle' }}
        run: |
          gh release download 1.8.1 --pattern '*.jar' --repo google/bundletool
          java -jar bundletool*.jar build-apks --bundle=build/app/outputs/bundle/release/app-release.aab --output=apks.apks --mode=universal
          unzip apks.apks
          mv universal.apk choose-food-1.0.${{ github.run_number }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ matrix.target == 'appbundle' }}
        uses: actions/upload-artifact@v2
        with:
          path: '*.apk'

      - if: ${{ matrix.target == 'appbundle' }}
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ matrix.target == 'appbundle' && github.ref == 'refs/heads/main' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            build/app/outputs/bundle/release/app-release.aab
            *.apk
      - if: ${{ matrix.target == 'web' }}
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: build/web
