# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: Mause/ChooseFood/.github/workflows/build.yaml@apks

  build_appbundle:
    runs-on: ubuntu-latest

    steps:
      - uses: Mause/ChooseFood/.github/workflows/build.yaml@apks
      - uses: actions/upload-artifact@v2
      - run: flutter build appbundle --build-number ${{ github.run_number }}
      - run: |
          gh release download 1.8.1 --pattern '*.jar' --repo google/bundletool
          java -jar bundletool*.jar build-apks --bundle=build/app/outputs/bundle/release/app-release.aab --output=apks.apks --mode=universal
          unzip apks.apks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: java -jar bundletool-all.1.8.1.jar build-apks --bundle=build/app/outputs/bundle/release/app-release.aab --output=apks
      - uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
      - uses: actions/upload-artifact@v2
        with:
          path: universal.apk
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            build/app/outputs/bundle/release/app-release.aab
            unniversal.apk

  build_web:
    runs-on: ubuntu-latest

    steps:
      - uses: Mause/ChooseFood/.github/workflows/build.yaml@apks
      - name: Build
        run: flutter build web
      - uses: actions/upload-artifact@v2
        with:
          name: web
          path: build/web
