# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

env:
  flutter_version: '2.13.0-0.4.pre'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-${{ hashFiles('pubspec.lock') }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'beta'

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter pub run build_runner build

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .

      - uses: invertase/github-action-dart-analyzer@v1

      - name: Unit tests
        run: flutter test --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }} test/

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test failures
          path: test/failures
      #- run: flutter packages pub run sentry_dart_plugin
      #  env:
      #    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  build_releases:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        target: [appbundle, web]

    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-${{ hashFiles('pubspec.lock') }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: beta
      - name: Install dependencies
        run: flutter pub get
      - name: Prebuild
        run: flutter pub run build_runner build
      - if: ${{ matrix.target == 'appbundle' }}
        run: echo "$SIGNING_KEY" | openssl base64 -d > android/app/key.store
        shell: bash
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - if: ${{ matrix.target == 'appbundle' }}
        run: |
          flutter build appbundle \
            --build-number ${{ github.run_number }} \
            --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }} \
            --dart-define=GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} \
            --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --dart-define=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
            --no-shrink
        env:
          SIGNING_KEY: key.store
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - if: ${{ matrix.target == 'web' }}
        run: flutter build web
#       - if: ${{ matrix.target == 'appbundle' }}
#         uses: r0adkll/upload-google-play@v1.0.15
#         with:
#           serviceAccountJsonPlainText: ${{ secrets.SERVICE_TOKEN }}
#           packageName: me.mause.choosefood
#           releaseFiles: build/app/outputs/bundle/release/app-release.aab
#           track: internal
#           changesNotSentForReview: true
#           status: draft
      - if: ${{ matrix.target == 'appbundle' }}
        run: |
          gh release download 1.8.1 --pattern '*.jar' --repo google/bundletool
          java -jar bundletool*.jar build-apks \
             --bundle=build/app/outputs/bundle/release/app-release.aab \
             --output=apks.apks \
             --mode=universal \
             --ks android/app/key.store \
             --ks-key-alias upload \
             --ks-pass pass:${{ secrets.KEY_STORE_PASSWORD}} \
             --key-pass pass:${{ secrets.KEY_PASSWORD }}
          unzip apks.apks
          mv universal.apk me.mause.choosefood_${{ github.run_number }}.apk
          find . -name "*.apk" -exec echo "APK: {}" \; -exec sh -c 'keytool -printcert -jarfile "{}"' \;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ matrix.target == 'appbundle' }}
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: '*.apk'

      - if: ${{ matrix.target == 'appbundle' }}
        uses: actions/upload-artifact@v3
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab

#       - uses: "marvinpinto/action-automatic-releases@latest"
#         if: ${{ matrix.target == 'appbundle' && github.ref == 'refs/heads/main' }}
#         with:
#           repo_token: "${{ secrets.GITHUB_TOKEN }}"
#           automatic_release_tag: "builds/androiddeploy/1.0.0+${{ github.run_number }}"
#           prerelease: false
#           title: "Build 1.0.0+${{ github.run_number }}"
#           files: |
#             build/app/outputs/bundle/release/app-release.aab
#             *.apk

      - if: ${{ matrix.target == 'web' }}
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web

  verify_formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-${{ hashFiles('pubspec.lock') }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          flutter-version: ${{ env.flutter_version }}

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

  integration_tests:
    runs-on: macos-latest
    if: false

    strategy:
      matrix:
        api-level: [31]

    steps:
      - uses: actions/checkout@v3

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-2021-11-25

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        timeout-minutes: 8
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          avd-name: android
          script: echo "Generated AVD snapshot for caching."
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          ram-size: 3072M

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-${{ hashFiles('pubspec.lock') }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'beta'

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter pub run build_runner build

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt-hotspot

      - run: flutter build apk --debug

      - name: Integration tests
        uses: reactivecircus/android-emulator-runner@v2
        timeout-minutes: 10
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          avd-name: android
          ram-size: 3072M
          script: |
            echo "::group::Integration tests"
            flutter drive --driver=test_driver/integration_test.dart --target=integration_test/screenshot_test.dart -d emulator-5554 --trace-startup
            echo "::endgroup::"

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/

      - name: Upload failed tests
        if: always() && github.ref != 'refs/heads/main'
        uses: edunad/actions-image@v1.0.1
        with:
            path: './screenshots/*'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            title: 'Screenshots'

  note_changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - run: |
          bundle exec fastlane create_notes build_number:${{ github.run_number }}

  create_github_release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - build_releases
     # - integration_tests
      - build_windows
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          name: appbundle
          path: '*.aab'

      - uses: actions/download-artifact@v3
        with:
          name: apk
          path: '*.apk'

      - uses: actions/download-artifact@v3
        with:
          name: msix
          path: '*.msix'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.aab
            *.apk
            *.msix

  publish:
    runs-on: ubuntu-latest
    needs: create_github_release
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - run: echo $SERVICE_TOKEN > secrets.json
        shell: bash
        env:
          SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}

      - uses: actions/download-artifact@v3
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/

      - run: |
          ls -a build/app/outputs/bundle/release/
          git config user.name "GitHub Actions"
          git config user.email "ga@mause.me"

      - run: bundle exec fastlane android deploy build_number:${{ github.run_number }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}

  publish_to_fdroid:
    runs-on: ubuntu-latest
    needs: publish

    steps:
    - name: Deploy Stage
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.TRIGGER_FDROID_UPDATE }}
        script: |
          await github.rest.repos.createDispatchEvent({
            owner: 'Mause',
            repo: 'fdroidrepo',
            event_type: 'repository_dispatch'
          });

  build_windows:
    runs-on: windows-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-${{ hashFiles('pubspec.lock') }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'beta'

      - run: flutter config --enable-windows-desktop
      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter pub run build_runner build

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .

      - uses: invertase/github-action-dart-analyzer@v1

      - name: Unit tests
        run: flutter test --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }} test/

      - run: flutter build windows
      - run: flutter pub run msix:create
      - uses: actions/upload-artifact@v3
        with:
          name: msix
          path: build\windows\runner\**\*.msix
