# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: Mause/ChooseFood/.github/workflows/reuse.yaml@main

  build_releases:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        target: [appbundle, web]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Install dependencies
        run: flutter pub get
      - name: Prebuild
        run: flutter pub run build_runner build
      - name: Build ${{ matrix.target }}
        run: flutter build ${{ matrix.target }}
      - run: |
          wget https://github.com/google/bundletool/releases/download/1.8.1/bundletool-all-1.8.1.jar
          java -jar bundletool-all-1.8.1.jar version
      - if: ${{ matrix.target == 'appbundle' }}
        run: java -jar bundletool-all-1.8.1.jar build-apks --bundle=build/app/outputs/bundle/release/app-release.aab --output=apks
      - if: ${{ matrix.target == 'appbundle' }}
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ matrix.target == 'appbundle' && github.ref == 'refs/heads/main' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            build/app/outputs/bundle/release/app-release.aab
            apks/*
      - if: ${{ matrix.target == 'web' }}
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: build/web
