on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}

name: Update client
jobs:
  update_client:
    name: Update client
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-${{ hashFiles('pubspec.lock') }}

      - uses: subosito/flutter-action@v1
        with:
          channel: beta

      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
      - name: Update types
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            npx @openapitools/openapi-generator-cli generate -i ${{ secrets.SUPABASE_URL }}/rest/v1/?apikey=${{ secrets.SUPABASE_KEY }} -o packages/supabase_client -g dart --additional-properties=pubName=supabase_client
            rm -rf packages/supabase_client/test
            flutter pub get
          COMMIT_MESSAGE: "chore: update ${{ matrix.name }} client"
          COMMIT_NAME: "GitHub Actions"
          COMMIT_EMAIL: "example@example.com"
          PR_BRANCH_NAME: "chore-${{ matrix.name }}-update-client-${PR_ID}"
          PR_TITLE: "chore: update ${{ matrix.name }} client"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
