on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}

name: Update openapi swagger
jobs:
  update_openapi:
    name: Update openapi swagger
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-${{ hashFiles('pubspec.lock') }}

      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Install dependencies
        run: flutter pub get
      - name: Update openapi swagger
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            mkdir -p lib/swagger
            curl ${{ secrets.SUPABASE_URL }}/rest/v1/?apikey=${{ secrets.SUPABASE_KEY }} | jq > lib/swagger/openapi.json
            tree
            python3 ./.github/workflows/add_point.py
            flutter pub run build_runner build --delete-conflicting-outputs
            git add -f lib/generated_code
          COMMIT_MESSAGE: "chore: update ${{ matrix.name }} client"
          COMMIT_NAME: "GitHub Actions"
          COMMIT_EMAIL: "example@example.com"
          PR_BRANCH_NAME: "chore-${{ matrix.name }}-update-client-${PR_ID}"
          PR_TITLE: "chore: update ${{ matrix.name }} client"
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
