name: Flutter

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-${{ hashFiles('pubspec.lock') }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.9.0'
          channel: 'beta'

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter pub run build_runner build

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .

      - uses: invertase/github-action-dart-analyzer@v1

      - name: Unit tests
        run: flutter test --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }} test/

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test failures
          path: test/failures
      #- run: flutter packages pub run sentry_dart_plugin
      #  env:
      #    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
