name: Flutter

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter pub run build_runner build

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze

      - name: Unit tests
        run: flutter test --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }} test/

      - uses: nanasess/setup-chromedriver@b392eaf03aa077c2e929bc94c71b65dc91ef1923
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Integration tests
        run: flutter drive  -d web-server
